#!/bin/bash -e
# vim: set tabstop=8 shiftwidth=4 softtabstop=4 expandtab smarttab colorcolumn=80:
#
# Copyright (c) 2016 Red Hat, Inc.
# Author: Harald Hoyer <harald@redhat.com>
# Author: Nathaniel McCallum <npmccallum@redhat.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

UUID=cb6e8904-81ff-40da-a84a-07ab9ab5715e

shopt -s nullglob

while true; do
    previous=(${questions[@]})
    questions=(/run/systemd/ask-password/ask.*)
    allprocessed=true

    for question in ${questions[@]}; do
        d=
        s=

	# check if we previously processed this file
        printf -- '%s\n' "${previous[@]}" | grep -q $question && continue
	allprocessed=false

	# check if question was answered by another PasswordAgent
        [ -e "$question" ] || continue
        while read line; do
            case "$line" in
                Id=cryptsetup:*) d="${line##Id=cryptsetup:}";;
                Socket=*) s="${line##Socket=}";;
            esac
        done < "$question"

        [ -z "$d" -o -z "$s" ] && continue

        # If the device is not initialized, sliently skip it.
        luksmeta test -d "$d" || continue

        while read -r slot state uuid; do
            [ "$state" != "active" ] && continue
            [ "$uuid" != "$UUID" ] && continue

            if pt="`luksmeta load -d $d -s $slot -u $UUID | clevis decrypt`"; then
                echo -n "+$pt" | nc -U -u --send-only "$s"
                break
            fi
        done < <(luksmeta show -d "$d")
    done

    $allprocessed && break
done
