#!/bin/bash -xe
# vim: set tabstop=8 shiftwidth=4 softtabstop=4 expandtab smarttab colorcolumn=80:
#
# Copyright (c) 2026 Red Hat, Inc.
# Author: Sergio Arroutbi <sarroutb@redhat.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

. tang-pqc-common-test-functions

on_exit() {
    exit_status=$?
    tang_stop "${TMP}"
    [ -d "$TMP" ] && rm -rf "$TMP"
    exit "${exit_status}"
}

trap 'on_exit' EXIT

TMP="$(mktemp -d)"

tang_pqc_sanity_check

tang_run "${TMP}" sig exc
port=$(tang_get_port "${TMP}")

tang_pqc_check_version "${port}" \
    || skip_test "Tang server does not support hybrid PQC"

thp="$(jose jwk thp -i "$TMP/db/sig.jwk")"
url="http://localhost:${port}"

# Basic encrypt/decrypt round-trip with thp.
cfg="$(printf '{"url":"%s","thp":"%s"}' "$url" "$thp")"
enc="$(echo -n "hi" | clevis encrypt tang-pqc "$cfg")"
dec="$(echo -n "$enc" | clevis decrypt)"
test "$dec" == "hi"

# Encrypt/decrypt round-trip with auto-trust (-y).
cfg="$(printf '{"url":"%s"}' "$url")"
enc="$(echo -n "hello pqc" | clevis encrypt tang-pqc "$cfg" -y)"
dec="$(echo -n "$enc" | clevis decrypt)"
test "$dec" == "hello pqc"

# Verify the JWE header contains tang-pqc pin metadata.
hdr="$(echo -n "$enc" | cut -d. -f1)"
jhd="$(jose b64 dec -i- <<< "$hdr")"
pin="$(jose fmt -j- -Og clevis -g pin -u- <<< "$jhd")"
test "$pin" == "tang-pqc"

# Verify clevis.tang-pqc header is present.
jose fmt -j- -Og clevis -g tang-pqc -Oo- <<< "$jhd" >/dev/null

# Server down must cause decrypt to fail.
tang_stop "${TMP}"
! echo "$enc" | clevis decrypt
