#!/bin/bash -xe
# vim: set tabstop=8 shiftwidth=4 softtabstop=4 expandtab smarttab colorcolumn=80:
#
# Copyright (c) 2026 Red Hat, Inc.
# Author: Sergio Arroutbi <sarroutb@redhat.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

. tang-pqc-common-test-functions

on_exit() {
    exit_status=$?
    tang_stop "${TMP}"
    [ -d "$TMP" ] && rm -rf "$TMP"
    exit "${exit_status}"
}

trap 'on_exit' EXIT

TMP="$(mktemp -d)"

tang_pqc_sanity_check

tang_run "${TMP}" sig exc
port=$(tang_get_port "${TMP}")

tang_pqc_check_version "${port}" \
    || skip_test "Tang server does not support hybrid PQC"

url="http://localhost:${port}"

# Missing url property must fail.
! echo -n "fail" | clevis encrypt tang-pqc '{}'

# Unreachable server must fail.
cfg='{"url":"http://localhost:1"}'
! echo -n "fail" | clevis encrypt tang-pqc "$cfg" -y

# Wrong thumbprint must fail.
cfg="$(printf '{"url":"%s","thp":"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"}' \
       "$url")"
! echo -n "fail" | clevis encrypt tang-pqc "$cfg"

# Tampered JWE must fail to decrypt.
thp="$(jose jwk thp -i "$TMP/db/sig.jwk")"
cfg="$(printf '{"url":"%s","thp":"%s"}' "$url" "$thp")"
enc="$(echo -n "tamper test" | clevis encrypt tang-pqc "$cfg")"

# Flip a character in the ciphertext portion (fifth dot-separated field).
tampered="$(echo -n "$enc" | sed 's/\(.*\.\)\(.\)\(.*\)/\1X\3/')"
! echo -n "$tampered" | clevis decrypt
