#!/bin/sh -x

trap 'exit' ERR

e=`echo hi | ./clevis-encrypt test '{"fail": false}'`
d=`echo $e | ./clevis-decrypt`
test "$d" == "hi"

e=`echo hi | ./clevis-encrypt test '{"fail": true}'`
! echo $e | ./clevis-decrypt

