#!/bin/sh -ex

e=`echo hi | clevis encrypt sss '{"t":1,"pins":{"test":[{},{}]}}'`
d=`echo $e | clevis decrypt`
test "$d" == "hi"

e=`echo hi | clevis encrypt sss '{"t":1,"pins":{"test":[{},{"fail":true}]}}'`
d=`echo $e | clevis decrypt`
test "$d" == "hi"

e=`echo hi | clevis encrypt sss '{"t":1,"pins":{"test":[{"fail":true},{"fail":true}]}}'`
! echo $e | clevis decrypt

e=`echo hi | clevis encrypt sss '{"t":2,"pins":{"test":[{},{}]}}'`
d=`echo $e | clevis decrypt`
test "$d" == "hi"

e=`echo hi | clevis encrypt sss '{"t":2,"pins":{"test":[{},{"fail":true}]}}'`
! echo $e | clevis decrypt

e=`echo hi | clevis encrypt sss '{"t":2,"pins":{"test":[{"fail":true},{"fail":true}]}}'`
! echo $e | clevis decrypt
