#!/bin/sh -ex

e=`echo hi | ${top_builddir:-.}/clevis encrypt sss '{"t": 1, "pins": {"test": [{"fail": false}, {"fail": false}]}}'`
d=`echo $e | ${top_builddir:-.}/clevis decrypt`
test "$d" == "hi"

e=`echo hi | ${top_builddir:-.}/clevis encrypt sss '{"t": 1, "pins": {"test": [{"fail": true}, {"fail": false}]}}'`
d=`echo $e | ${top_builddir:-.}/clevis decrypt`
test "$d" == "hi"

e=`echo hi | ${top_builddir:-.}/clevis encrypt sss '{"t": 1, "pins": {"test": [{"fail": false}, {"fail": true}]}}'`
d=`echo $e | ${top_builddir:-.}/clevis decrypt`
test "$d" == "hi"

e=`echo hi | ${top_builddir:-.}/clevis encrypt sss '{"t": 1, "pins": {"test": [{"fail": true}, {"fail": true}]}}'`
! echo $e | ${top_builddir:-.}/clevis decrypt

e=`echo hi | ${top_builddir:-.}/clevis encrypt sss '{"t": 2, "pins": {"test": [{"fail": false}, {"fail": false}]}}'`
d=`echo $e | ${top_builddir:-.}/clevis decrypt`
test "$d" == "hi"

e=`echo hi | ${top_builddir:-.}/clevis encrypt sss '{"t": 2, "pins": {"test": [{"fail": true}, {"fail": false}]}}'`
! echo $e | ${top_builddir:-.}/clevis decrypt

e=`echo hi | ${top_builddir:-.}/clevis encrypt sss '{"t": 2, "pins": {"test": [{"fail": false}, {"fail": true}]}}'`
! echo $e | ${top_builddir:-.}/clevis decrypt

e=`echo hi | ${top_builddir:-.}/clevis encrypt sss '{"t": 2, "pins": {"test": [{"fail": true}, {"fail": true}]}}'`
! echo $e | ${top_builddir:-.}/clevis decrypt

