#!/bin/sh -ex

e=`echo hi | src/clevis-encrypt sss '{"t": 1, "pins": {"test": [{"fail": false}, {"fail": false}]}}'`
d=`echo $e | src/clevis-decrypt`
test "$d" == "hi"

e=`echo hi | src/clevis-encrypt sss '{"t": 1, "pins": {"test": [{"fail": true}, {"fail": false}]}}'`
d=`echo $e | src/clevis-decrypt`
test "$d" == "hi"

e=`echo hi | src/clevis-encrypt sss '{"t": 1, "pins": {"test": [{"fail": false}, {"fail": true}]}}'`
d=`echo $e | src/clevis-decrypt`
test "$d" == "hi"

e=`echo hi | src/clevis-encrypt sss '{"t": 1, "pins": {"test": [{"fail": true}, {"fail": true}]}}'`
! echo $e | src/clevis-decrypt

e=`echo hi | src/clevis-encrypt sss '{"t": 2, "pins": {"test": [{"fail": false}, {"fail": false}]}}'`
d=`echo $e | src/clevis-decrypt`
test "$d" == "hi"

e=`echo hi | src/clevis-encrypt sss '{"t": 2, "pins": {"test": [{"fail": true}, {"fail": false}]}}'`
! echo $e | src/clevis-decrypt

e=`echo hi | src/clevis-encrypt sss '{"t": 2, "pins": {"test": [{"fail": false}, {"fail": true}]}}'`
! echo $e | src/clevis-decrypt

e=`echo hi | src/clevis-encrypt sss '{"t": 2, "pins": {"test": [{"fail": true}, {"fail": true}]}}'`
! echo $e | src/clevis-decrypt

