#!/bin/bash -x

trap 'exit' ERR

e=`echo -n hi | clevis encrypt test '{}'`
d=`echo -n "$e" | clevis decrypt`
test "$d" == "hi"

e=`echo -n hi | clevis encrypt test '{"fail":true}'`
! echo "$e" | decrypt
