#!/bin/sh -x

trap 'exit' ERR

PORT=`shuf -i 1024-65535 -n 1`

./pin-httpd $PORT &
export PID=$!
sleep 0.25

function onerr() {
    kill -9 $PID
    ! wait $PID
    exit 1
}

trap 'onerr' ERR

e=`echo hi | ${top_builddir:-.}/clevis encrypt http "{\"url\": \"http://localhost:${PORT}/foo\"}"`
d=`echo $e | ${top_builddir:-.}/clevis decrypt`
test "$d" == "hi"

kill -9 $PID
! wait $PID

trap 'exit' ERR

! echo $e | ${top_builddir:-.}/clevis decrypt
