#!/bin/sh -x

trap 'exit' ERR

e=`echo hi | src/clevis-encrypt test '{"fail": false}'`
d=`echo $e | src/clevis-decrypt`
test "$d" == "hi"

e=`echo hi | src/clevis-encrypt test '{"fail": true}'`
! echo $e | src/clevis-decrypt

