#!/bin/bash -ex
#
# Copyright (c) 2026 Oldřich Jedlička
#
# Author: Oldřich Jedlička <oldium.pro@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

TEST=$(basename "${0}")
. zfs-common-test-functions

zfs_check_requirements

on_exit() {
    zfs_destroy_pool "${POOL}"
    [ -d "${TMP}" ] && rm -rf "${TMP}"
}

trap 'on_exit' EXIT

TMP="$(mktemp -d)"
POOL="$(zfs_new_pool "${TMP}")"
DS="${POOL}/enc"
head -c 32 /dev/urandom > "${TMP}/key"
zfs create -o encryption=on -o keyformat=raw -o keylocation="file://${TMP}/key" \
    -o mountpoint=none "${DS}" || error "${TEST}: Unable to create ${DS}"

if out=$(clevis zfs bind -k "${TMP}/key" -d "${DS}" null '{}' 2>&1); then
    error "${TEST}: Binding a raw key succeeded"
fi
[[ "${out}" == *"raw keyformat is not supported"* ]] \
    || error "${TEST}: Unexpected error: ${out}"
