.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "CLEVIS\-LUKS\-UNLOCK" "1" "September 2017" "" ""
.
.SH "NAME"
\fBclevis\-luks\-unlock\fR \- Unlocks a LUKSv1 device bound with a Clevis policy
.
.SH "SYNOPSIS"
\fBclevis luks unlock\fR \-d DEV [\-n NAME]
.
.SH "OVERVIEW"
The \fBclevis luks unlock\fR command unlocks a LUKSv1 device using its already provisioned Clevis policy\. For example:
.
.IP "" 4
.
.nf

$ clevis luks unlock \-d /dev/sda
.
.fi
.
.IP "" 0
.
.SH "OPTIONS"
.
.TP
\fB\-d\fR \fIDEV\fR
The LUKS device to unlock
.
.TP
\fB\-n\fR \fINAME\fR
The name to give the unlocked device node
.
.SH "AUTHOR"
Nathaniel McCallum <npmccallum@redhat\.com>
.
.SH "SEE ALSO"
\fBclevis\-luks\-bind\fR(1)
