'\" t
.\"     Title: clevis-luks-bind
.\"    Author: [FIXME: author] [see http://www.docbook.org/tdg5/en/html/author]
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 07/12/2018
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "CLEVIS\-LUKS\-BIND" "1" "07/12/2018" "\ \&" "\ \&"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
clevis-luks-bind \- Bind a LUKSv1 device using the specified policy
.SH "SYNOPSIS"
.sp
\fBclevis luks bind\fR [\-f] \-d DEV [\-s SLT] [\-k KEY] PIN CFG
.SH "OVERVIEW"
.sp
The \fBclevis luks bind\fR command binds a LUKSv1 device using the specified policy\&. This is accomplished with a simple command:
.sp
.if n \{\
.RS 4
.\}
.nf
$ clevis luks bind \-d /dev/sda tang \*(Aq{"url":\&.\&.\&.}\*(Aq
.fi
.if n \{\
.RE
.\}
.sp
This command performs four steps:
.sp
.RS 4
.ie n \{\
\h'-04' 1.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  1." 4.2
.\}
Creates a new key with the same entropy as the LUKS master key\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 2.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  2." 4.2
.\}
Encrypts the new key with Clevis\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 3.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  3." 4.2
.\}
Stores the Clevis JWE in the LUKS header with LUKSMeta\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 4.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  4." 4.2
.\}
Enables the new key for use with LUKS\&.
.RE
.sp
This disk can now be unlocked with your existing password as well as with the Clevis policy\&. You will additionally need to enable one or more of the Clevis LUKS unlockers\&. See \fBclevis\-luks\-unlockers\fR(7)\&.
.SH "OPTIONS"
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB\-f\fR
: Do not prompt for LUKSMeta initialization
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB\-d\fR
\fIDEV\fR
: The LUKS device on which to perform binding
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB\-s\fR
\fISLT\fR
: The LUKSMeta slot to use for metadata storage
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB\-k\fR
\fIKEY\fR
: Non\-interactively read LUKS password from KEY file
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB\-k\fR
\- : Non\-interactively read LUKS password from standard input
.RE
.SH "CAVEATS"
.sp
This command does not change the LUKS master key\&. This implies that if you create a LUKS\-encrypted image for use in a Virtual Machine or Cloud environment, all the instances that run this image will share a master key\&. This is extremely dangerous and should be avoided at all cost\&.
.sp
This is not a limitation of Clevis but a design principle of LUKS\&. If you wish to have encrypted root volumes in the cloud, you will need to make sure that you perform the OS install method for each instance in the cloud as well\&. The images cannot be shared without also sharing a master key\&.
.SH "SEE ALSO"
.sp
\fBclevis\-luks\-unlockers\fR(7), \fBclevis\-encrypt\-http\fR(1), \fBclevis\-encrypt\-tang\fR(1), \fBclevis\-encrypt\-sss\fR(1), \fBclevis\-decrypt\fR(1)
