.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "CLEVIS\-DECRYPT" "1" "June 2017" "" ""
.
.SH "NAME"
\fBclevis\-decrypt\fR \- Decrypts using the policy defined at encryption time
.
.SH "SYNOPSIS"
\fBclevis decrypt\fR CONFIG \fIJWE\fR PT
.
.SH "OVERVIEW"
The \fBclevis decrypt\fR command decrypts data using the policy defined at encryption time\. The specific decryption pin is inferred during decryption\. There are no parameters\.
.
.SH "AUTHOR"
Nathaniel McCallum <npmccallum@redhat\.com>
.
.SH "SEE ALSO"
\fBclevis\-decrypt\fR(1)
