#!/bin/sh

set -e

# Copyright (c) 2020 Christoph Biedl
# Author: Christoph Biedl <debian.axhn@manchmal.in-ulm.de>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

TMP="$(mktemp -d)"
# shellcheck disable=SC2064 # Expanding TMP right now is intended
trap "rm -rf \"$TMP\"" EXIT

cfg="$(printf '{"name":"%s"}' "$TMP/key")"
inp='hi'
enc="$(printf '%s' "$inp" | clevis encrypt file "$cfg")"
dec="$(printf '%s' "$enc" | clevis decrypt)"
test "$dec" = "$inp"
