#!/bin/bash
# vim: set tabstop=8 shiftwidth=4 softtabstop=4 expandtab smarttab colorcolumn=80:
#
# Copyright (c) 2017 Shawn Rose
# Author: Shawn Rose <shawnandrewrose@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

[ $1 == "prereqs" ] && exit 0 # We don't have any

. /usr/share/initramfs-tools/hook-functions

# Why am I copying all the stuff that's normally in /usr/local/bin/ to /usr/bin?
# Because /usr/local/bin isn't in path, and even if I add it TO path in /init
# the findexe function in clevis fails to find anything.
copy_exec /usr/local/bin/clevis-decrypt-http /usr/bin/clevis-decrypt-http
copy_exec /usr/local/bin/clevis-decrypt-tang /usr/bin/clevis-decrypt-tang
copy_exec /usr/local/bin/clevis-decrypt-sss /usr/bin/clevis-decrypt-sss
copy_exec /usr/local/bin/clevis-decrypt /usr/bin/clevis-decrypt
copy_exec /usr/local/bin/luksmeta /usr/bin/luksmeta
copy_exec /usr/local/bin/clevis /usr/bin/clevis
copy_exec /usr/local/bin/jose /usr/bin/jose
copy_exec /usr/bin/curl
copy_exec /bin/bash
