#!/bin/bash
set -euo pipefail

SUMMARY="Unbinds a ZFS dataset (remove clevis)"

usage() {
	cat >&2 <<-USAGE_END
		Usage: clevis zfs unbind [-f] [-k KEY] -d DATASET [-a]

		$SUMMARY:

		  -f          Force unbinding dataset
		  -d DATASET  The ZFS dataset on which to perform unbinding

		  -k KEY      Non-interactively read ZFS password from KEY file
		  -k -        Non-interactively read ZFS password from standard input

	USAGE_END
}

main() {
	if [ $# -eq 1 ] && [ "${1:-}" == "--summary" ]; then
		echo "$SUMMARY"
		exit 0
	fi

	local dataset
	local key
	while getopts ":hfd:k:" o; do
		case "$o" in
		d) dataset="$OPTARG";;
		k) key="$OPTARG";;
		*) error "unrecognized argument: -${OPTARG}";;
		esac
	done

	if [ -z "${dataset:-""}" ]; then
		error "did not specify a dataset!"
	fi

	if ! zfs_is_bound "${dataset}"; then
		error "dataset is not bound with Clevis: ${dataset}"
	fi

	echo >&2 "Loading existing key... "
	local existing_key="$(load_key "${dataset}" "${key}")"

	if ! zfs_test_key "${dataset}" <<<"${existing_key}"; then
		error "given key does not unlock ${dataset}"
	fi

	echo >&2 -n 'Wiping Clevis data... '
	zfs_wipe_clevis_data "${dataset}"
	echo >&2 'ok'
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
	. clevis-zfs-common-functions
	main "${@}"
fi
