#!/bin/bash

# zfs user properties are limited to 8192 bytes
zfs_userprop_max_size=8000

zfs_userprop_prefix='latchset.clevis'
zfs_data_prop="${zfs_userprop_prefix}:data"
zfs_status_prop="${zfs_userprop_prefix}:status"

# defaults to getting just the value of the given property and only when it is set directly on the dataset ("local")
zfs_get_prop() {
	local dataset="${1}"
	local prop="${2}"
	shift 2
	zfs get "${prop}" "${dataset}" -H -o value -slocal "${@}"
}

zfs_load_key() {
	local dataset="${1}"
	local args=( "-L" "prompt" )
	if [[ -n "${2:-}" ]]; then
		args+=( "-n" )
	fi
	zfs load-key "${args[@]}" "${dataset}" >/dev/null
}

zfs_test_key() {
	zfs_load_key "${1}" 'dry_run'
}

zfs_is_bound() {
	local dataset="${1}"
	[[ "$(zfs_get_prop "${dataset}" "${zfs_status_prop}" )" == 'bound' ]]
}

# we can only load keys on encryptionroots
# it does not make sense to add a binding elsewhere
zfs_is_encryptionroot() {
	local dataset="${1}"
	[[ "$(zfs_get_prop "${dataset}" 'encryptionroot' -snone )" == "${dataset}" ]]
}

# does it even exist?
zfs_is_dataset() {
	local dataset="${1}"
	zfs_get_property "${dataset}" 'name' -snone &>/dev/null
}

check_valid_dataset() {
	local dataset="${1}"

	if ! zfs_is_dataset "${dataset}"; then
		error "${dataset} is not a zfs dataset!"
	fi

	if ! zfs_is_encryptionroot "${dataset}"; then
		error "given dataset is not an encryptionroot: ${dataset}"
	fi

	# The key is passed through shell variables, which cannot hold raw bytes
	if [[ "$(zfs_get_prop "${dataset}" 'keyformat' -snone)" == 'raw' ]]; then
		error "raw keyformat is not supported: ${dataset}"
	fi
}


# functions to deal with I/O to the user
load_key() {
	local dataset="${1}"
	local key="${2?need keyinput argument}"

	# Get the existing passphrase/keyfile.
	local existing_key
	local keyfile

	case "${key}" in
	"") IFS= read -r -s -p "Enter existing ZFS password for ${dataset}: " existing_key;
		echo >&2
		;;
	 -) IFS= read -r -s -p "" existing_key;;
	 *) keyfile="${key}"
		if [ -r "${keyfile}" ]; then
			existing_key="$(< "${keyfile}")"
		else
			error "cannot read key file '${keyfile}'"
		fi
		;;
	esac
	echo "${existing_key}"
}

error() {
	echo >&2 -e "ERROR: ${*}"
	usage
	exit 1
}


# functions to deal with too large Clevis data for a single ZFS property
########################################################################

cut_into_chunks() {
	fold -w "${zfs_userprop_max_size}"
}

zero_pad() {
	local width="${1}"; shift
	printf "%0${width}d " "${@}"
}


# functions to add/remove a Clevis binding
#########################################
zfs_bind_clevis_data() {
	local dataset="${1}"
	local clevis_data="${2}"

	echo >&2 -n 'binding new Clevis data... '
	clevis_chunks=( $(cut_into_chunks <<<"${clevis_data}") )
	last_index="$(( "${#clevis_chunks[@]}" - 1 ))"
	width="${#last_index}"

	local chunk chunk_num
	for i in $(seq 0 "${last_index}" ); do
		chunk="${clevis_chunks[${i}]}"
		# we add zero-padding so the props sort nicely when we want to combine
		# them when we unlock
		chunk_num="$(zero_pad "${i}" "${width}" )"

		# e.g. latchset.clevis:pin-01=chunk_data
		zfs set "${zfs_data_prop}-${chunk_num}=${chunk}" "${dataset}"
	done
	echo >&2 'ok'

	# check if unlocking works
	echo >&2 -n 'testing new Clevis data... '
	if ! (zfs_get_clevis_data "${dataset}" | clevis decrypt | zfs_test_key "${dataset}"); then
		zfs_wipe_clevis_data "${dataset}"
		error "could not unlock dataset with Clevis configuration: ${dataset}"
	fi
	echo >&2 'ok'

	zfs set "${zfs_status_prop}=bound" "${dataset}"
}

zfs_get_data_props() {
	local dataset="${1}"

	#property HAS to be set, otherwise the grep doesn't work
	local outputs="${2:-property}"

	zfs_get_prop "${dataset}" 'all' -o "${outputs}" | grep -F "${zfs_data_prop}" | sort
}

zfs_wipe_clevis_data() {
	local dataset="${1}"

	for prop in $(zfs_get_prop "${dataset}" 'all' -o property | grep -F "${zfs_userprop_prefix}" ); do
		zfs inherit "${prop}" "${dataset}"
	done
}

zfs_get_clevis_data() {
	local dataset="${1:?}"
	zfs_get_data_props "${dataset}" 'property,value' | sort | awk '{print $2}' | tr -d '\n'
}
