#!/bin/bash
set -euo pipefail

SUMMARY="Unlock a ZFS dataset using the saved clevis data"

function usage() {
	cat >&2 <<-USAGE_END
		Usage: clevis zfs unlock [-n] [-k KEY] -d DATASET PIN CFG

		$SUMMARY:

		  -t          Test the clevis configuration without unlocking
		  -d DATASET  The zfs dataset to unlock
		  -l LABEL    Use only this label to unlock (defaults to trying all labels): TODO

	USAGE_END
}

function main() {
	if [ $# -eq 1 -a "${1:-}" == "--summary" ]; then
		echo "$SUMMARY"
		exit 0
	fi

	local dataset
	local test_only=''
	local label=''
	while getopts ":d:l:t" o; do
		case "$o" in
		d) dataset="$OPTARG" ;;
		t) test_only=' (test)' ;;
		l) label="$OPTARG" ;;
		*) error "unrecognized argument: -${OPTARG}" ;;
		esac
	done

	if [ -z "${dataset:-""}" ]; then
		error "did not specify a device!"
	fi

	if ! zfs_is_bound "${dataset}"; then
		error "dataset is not bound with clevis: ${dataset}"
	fi

	local clevis_data password

	for label in $(zfs_get_labels "${dataset}" | tr ' ' '\n' | grep "^${label}(:|$)"); do
		echo >&2 -n "loading clevis data from label ${label}... "
		clevis_data="$(zfs_get_clevis_label "${dataset}" "${label}")"
		password="$(clevis decrypt <<<"${clevis_data}" || echo '' )"
		echo >&2 'ok'

		echo >&2 -n "unlocking ${dataset}${test_only}... "
		if echo "${password}" | zfs_load_key "${dataset}" "${test_only}"; then
			echo >&2 'ok'
			[[ -z "${test_only}" ]] && exit 0
		else
			echo >&2 "failed"
			continue
		fi
	done
	exit 1
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
	. clevis-zfs-common
	main "${@}"
fi
