#!/bin/bash
set -euo pipefail

SUMMARY="Binds a ZFS dataset using the specified policy"

usage() {
	cat >&2 <<-USAGE_END
		Usage: clevis zfs bind [-f] [-y] [-k KEY] -d DATASET [-l LABEL] PIN CFG

		$SUMMARY:

		  -f          Do not prompt when overwriting configuration
		  -y          Automatically answer yes for all questions
		  -d DATASET  The ZFS dataset on which to perform binding
		  -l LABEL    The label to use for this binding, "default" if not given. Valid characters: lowercase letters, numbers, underscores, dots and hyphens

		  -k KEY      Non-interactively read ZFS password from KEY file
		  -k -        Non-interactively read ZFS password from standard input

	USAGE_END
}

bind_zfs_dataset() {
	local dataset="${1}"
	local label="${2}"
	local pin="${3}"
	local cfg="${4}"
	local key="${5}"
	local overwrite="${6:-}"
	local yes="${7:-}"

	local existing_key clevis_data

	if [[ -z "${overwrite}" ]] && zfs_is_bound "${dataset}" "${label}"; then
		error "given label ${label} in dataset ${dataset} already has a Clevis binding, not overwriting."
	fi

	existing_key="$(read_passphrase "${dataset}" "${key}")"

	if ! zfs_test_key "${dataset}" <<<"${existing_key}"; then
		error "given key does not unlock ${dataset}"
	fi

	echo >&2 -n 'creating new Clevis data... '
	clevis_data="$(clevis encrypt "${pin}" "${cfg}" ${yes:+"${yes}"} <<<"${existing_key}")"
	echo >&2 'ok'

	if [[ -n "${overwrite}" ]] && zfs_is_bound "${dataset}" "${label}"; then
		zfs_unbind_clevis_label "${dataset}" "${label}"
		echo >&2 'unbound old clevis data'
	fi

	zfs_bind_clevis_label "${dataset}" "${label}" "${clevis_data}"
}

main() {
	if [ $# -eq 1 ] && [ "${1:-}" == "--summary" ]; then
		echo "$SUMMARY"
		exit 0
	fi

	local dataset
	local pin
	local cfg
	local label='default'
	local key=''
	local overwrite=''
	local yes=''
	while getopts ":hyfd:l:k:" o; do
		case "$o" in
		h) usage; exit 0;;
		y) yes='-y';;
		f) overwrite='yes';;
		d) dataset="$OPTARG";;
		l) label="$OPTARG";;
		k) key="$OPTARG";;
		*) error "unrecognized argument: -${OPTARG}";;
		esac
	done

	if [ -z "${dataset:-""}" ]; then
		error "did not specify a dataset!"
	fi

	check_valid_dataset "${dataset}"

	if ! is_valid_label "${label}"; then
		error "invalid label: ${label}"
	fi

	pin="${*:$((OPTIND++)):1}"
	if [ -z "$pin" ]; then
		error "did not specify a pin!"
	elif ! command -v "clevis-encrypt-${pin}" >/dev/null; then
		error "'$pin' is not a valid pin!"
	fi

	cfg="${*:$((OPTIND++)):1}"
	if [ -z "$cfg" ]; then
		error "did not specify a pin config!"
	fi

	bind_zfs_dataset "${dataset}" "${label}" "${pin}" "${cfg}" "${key}" "${overwrite}" "${yes}"
	echo >&2 "label ${label} on dataset ${dataset} is successfully bound"
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
	. clevis-zfs-common-functions
	main "${@}"
fi
