#!/bin/bash
set -euo pipefail

. clevis-zfs-common

SUMMARY="List zfs datasets that are bound with clevis [in dataset]"

function usage() {
	cat >&2 <<-USAGE_END
		Usage: clevis zfs list -d DATASET

		$SUMMARY:

	USAGE_END
}


main() {
	if [ $# -eq 1 -a "${1:-}" == "--summary" ]; then
		echo "$SUMMARY"
		exit 0
	fi

	local dataset
	while getopts "d:" o; do
		case "$o" in
		d) dataset="$OPTARG" ;;
		*) error "unrecognized argument: -${OPTARG}" ;;
		esac
	done

	echo >&2 "The following ZFS datasets have been bound with clevis:"
	zfs get -r -H -o name,value -slocal "${zfs_labels_prop}" ${dataset}
}

main "${@}"
