#!/bin/bash -ex
# vim: set tabstop=8 shiftwidth=4 softtabstop=4 expandtab smarttab colorcolumn=80:
#
# Copyright (c) 2019 Red Hat, Inc.
# Author: Sergio Correia <scorreia@redhat.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

TEST=$(basename "${0}")
. luks-common-test-functions

on_exit() {
    [ -d "${TMP}" ] && rm -rf "${TMP}"
}

trap 'on_exit' EXIT
trap 'exit' ERR

if ! luks2_supported; then
    error "{TEST}: LUKS2 is not supported."
fi

TMP="$(mktemp -d)"

ADV="${TMP}/adv.jws"
tang_create_adv "${TMP}" "${ADV}"
CFG="$(printf '{"url":"foobar","adv":"%s"}' "$ADV")"

# LUKS2.

DEV="${TMP}/luks2-device"
TOKEN_ID=5
new_device "luks2" "${DEV}"

if ! clevis luks bind -d "${DEV}" -t "$TOKEN_ID" tang "${CFG}" <<< "${DEFAULT_PASS}"; then
    error "${TEST}: Binding is expected to succeed when given a correct (${DEFAULT_PASS}) password."
fi

if ! cryptsetup token export --token-id=5 "${DEV}"; then
    error "${TEST}: Clevis did not add the LUKS2 token to the correct slot."
fi

# Empty password (issue #494)
DEV="${TMP}/luks2-device-empty-pw"
new_device "luks2" "${DEV}"

# Let's create an empty password.
printf '%s\n\n' "${DEFAULT_PASS}" | cryptsetup luksChangeKey \
    --force-password --batch-mode "${DEV}"

if ! clevis luks bind -d "${DEV}" tang "${CFG}" <<< ""; then
    error "${TEST}: Binding is expected to succeed when the password is empty."
fi
