#!/bin/bash -x
# vim: set ts=8 shiftwidth=4 softtabstop=4 expandtab smarttab colorcolumn=80:
#
# Copyright (c) 2020 Red Hat, Inc.
# Author: Sergio Correia <scorreia@redhat.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

TEST="${0}"
. tests-common-functions
. clevis-luks-common-functions

function on_exit() {
    [ -d "${TMP}" ] || return 0
    tang_stop "${TMP}"
    rm -rf "${TMP}"
}

trap 'on_exit' EXIT

export TMP=$(mktemp -d)

port=$(tang_new_random_port)
tang_run "${TMP}" "${port}"

url="http://localhost:${port}"
adv="${TMP}/adv"
tang_get_adv "${port}" "${adv}"

cfg=$(printf '{"url":"%s","adv":"%s"}' "$url" "$adv")

# LUKS2.
DEV="${TMP}/luks2-device"
new_device "luks2" "${DEV}"

SLT=1
if ! clevis luks bind -f -s "${SLT}" -d "${DEV}" tang "${cfg}" <<< "${DEFAULT_PASS}"; then
    error "${TEST}: Bind should have succeeded."
fi

# Now let's rotate the keys in the server and remove the old ones, so that we
# will be unable to unlock the volume using clevis and will have to provide
# manually a password for clevis luks regen.
tang_new_keys "${TMP}" "rotate-keys"
tang_remove_rotated_keys "${TMP}"

# Making sure we have two slots enabled.
enabled=$(clevis_luks_used_slots "${DEV}" | wc -l)
if [ "${enabled}" -ne 2 ]; then
    error "${TEST}: we should have two slots enabled (${enabled})."
fi

# Make sure we cannot unlock the device.
if clevis_luks_unlock_device_by_slot "${DEV}"; then
    error "${TEST}: we should NOT be able to unlock ${DEV}"
fi

# Now let's try regen.
if ! clevis luks regen -q -d "${DEV}" -s "${SLT}" <<< "${DEFAULT_PASS}"; then
    error "${TEST}: clevis luks regen failed"
fi

# Make sure we can unlock the device.
if ! clevis_luks_unlock_device_by_slot "${DEV}" "${SLT}"; then
    error "${TEST}: we should be able to unlock ${DEV}"
fi
