#!/bin/bash -ex
# vim: set ts=8 shiftwidth=4 softtabstop=4 expandtab smarttab colorcolumn=80:
#
# Copyright (c) 2020 Red Hat, Inc.
# Author: Sergio Correia <scorreia@redhat.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

TEST=$(basename "${0}")
. tests-common-functions

. clevis-luks-common-functions

on_exit() {
    [ ! -d "${TMP}" ] && return 0
    tang_stop "${TMP}"
    rm -rf "${TMP}"
}

trap 'on_exit' EXIT
trap 'on_exit' ERR

TMP="$(mktemp -d)"

port=$(get_random_port)
tang_run "${TMP}" "${port}" &
tang_wait_until_ready "${port}"

url="http://${TANG_HOST}:${port}"
adv="${TMP}/adv"
tang_get_adv "${port}" "${adv}"

cfg=$(printf '{"url":"%s","adv":"%s"}' "$url" "$adv")

# LUKS1.
DEV="${TMP}/luks1-device"
new_device "luks1" "${DEV}"

if ! clevis luks bind -f -d "${DEV}" tang "${cfg}" <<< "${DEFAULT_PASS}"; then
    error "${TEST}: Bind should have succeeded."
fi

if ! clevis_luks_unlock_device "${DEV}"; then
    error "${TEST}: we were unable to unlock ${DEV}."
fi

# Let's rotate the tang keys and add another binding with the new key.
tang_new_keys "${TMP}" "rotate-keys"

# Unlock should still work now.
if ! clevis_luks_unlock_device "${DEV}"; then
    error "${TEST}: we should still be able to unlock ${DEV}"
fi

# Now let's remove the rotated keys.
tang_remove_rotated_keys "${TMP}"

# Unlock should not work anymore.
if clevis_luks_unlock_dev "${DEV}"; then
    error "${TEST}: we should not be able to unlock ${DEV}"
fi

# Now let's add another binding with the new keys.
tang_get_adv "${port}" "${adv}" # Updating the advertisement.
if ! clevis luks bind -f -d "${DEV}" tang "${cfg}" <<< "${DEFAULT_PASS}"; then
    error "${TEST}: Bind should have succeeded."
fi

# Unlock should work again, using the new keys.
if ! clevis_luks_unlock_device "${DEV}"; then
    error "${TEST}: we should be able to unlock ${DEV} with the new keys"
fi
